# app/app.py
"""Streamlit application for handwritten digit recognition and GAN demo.
The app allows users to upload an image of a handwritten digit (28x28 or larger) and obtains a prediction using a
pre‑trained CNN classifier trained on MNIST. It also displays a grid of synthetic digits generated by the GAN.
"""

import streamlit as st
import torch
import torch.nn.functional as F
from pathlib import Path

# Local imports
from utils import set_seed
from app.utils import preprocess_image, load_image_from_tensor
from models.classifier import Classifier
from models.gan import Generator, GANTrainer

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
SEED = 42
set_seed(SEED)

# Paths to model checkpoints (these will be created after training)
CLASSIFIER_PATH = Path(__file__).parent.parent / "models" / "classifier.pth"
GENERATOR_PATH = Path(__file__).parent.parent / "models" / "generator.pth"

# Load classifier (if available)
if CLASSIFIER_PATH.is_file():
    classifier = Classifier().to(DEVICE)
    classifier.load_state_dict(torch.load(CLASSIFIER_PATH, map_location=DEVICE))
    classifier.eval()
else:
    classifier = None
    st.warning("Classifier checkpoint not found. Digit recognition will be unavailable until the model is trained and saved as `models/classifier.pth`.")

# Load generator for demo (if available)
if GENERATOR_PATH.is_file():
    generator = Generator(latent_dim=100).to(DEVICE)
    generator.load_state_dict(torch.load(GENERATOR_PATH, map_location=DEVICE))
    generator.eval()
else:
    generator = None
    st.info("GAN generator checkpoint not found – sample generation disabled.")

# ---------------------------------------------------------------------------
# Streamlit UI
# ---------------------------------------------------------------------------
st.set_page_config(page_title="Handwritten Digit Recognizer", layout="centered")
st.title("🖊️ Handwritten Digit Recognizer & GAN Demo")

st.markdown(
    "Upload an image of a handwritten digit (PNG/JPG). "
    "The app will preprocess the image to 28×28 grayscale, run it through a CNN classifier, "
    "and display the predicted digit with confidence."
)

uploaded_file = st.file_uploader("Choose an image…", type=["png", "jpg", "jpeg"])

if uploaded_file is not None:
    # Preprocess image
    tensor = preprocess_image(uploaded_file).to(DEVICE)
    # Show the processed image for visual confirmation
    st.subheader("Processed Image (28×28)")
    st.image(load_image_from_tensor(tensor), width=150)

    if classifier is not None:
        with torch.no_grad():
            logits = classifier(tensor)
            probs = F.softmax(logits, dim=1)
            pred = torch.argmax(probs, dim=1).item()
            confidence = probs[0, pred].item() * 100
        st.success(f"**Predicted Digit:** {pred}  
                    **Confidence:** {confidence:.1f}%")
    else:
        st.error("Classifier model not loaded; cannot make a prediction.")

# ---------------------------------------------------------------------------
# GAN sample generation demo
# ---------------------------------------------------------------------------
st.markdown("---")
st.header("🎨 GAN Sample Digits")
if generator is not None:
    # Generate a grid of 4x4 samples
    with torch.no_grad():
        samples = generator(torch.randn(16, 100, device=DEVICE))
    # De‑normalize to [0,1]
    samples = samples * 0.5 + 0.5
    # Convert to numpy for plotting
    import numpy as np
    import matplotlib.pyplot as plt
    grid = samples.cpu().numpy()
    fig, axes = plt.subplots(4, 4, figsize=(6, 6))
    for i, ax in enumerate(axes.flat):
        ax.imshow(grid[i][0], cmap='gray')
        ax.axis('off')
    st.pyplot(fig)
else:
    st.info("GAN generator not available – train the GAN and save `generator.pth` to view samples.")
